name: 'build'
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: 'build and push to dist branch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install deps
        run: npm install
      - name: build
        run: npm run build
      - name: clean up and push
        run: |
          git config --global user.email "chitacan@gmail.com"
          git config --global user.name "chitacan"
          git checkout --orphan dist
          rm -rf node_modules lib package.json package-lock.json .gitignore .github README.md
          git add .
          git commit -m "Deploy from ${GITHUB_SHA}" --quiet
          git push https://chitacan:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git dist --force

